#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Only the values that are safe on disk land here — the certificate, its
# password and the Sparkle private key go straight to GitHub and are never
# written to the filesystem.
ENV_FILE=".env.release"

SPARKLE_VERSION="2.10.0"
PUBLIC_KEY_FILE="Resources/sparkle-public-key.txt"
WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

banner "Keg release pipeline setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the tools this wizard needs."

cd "$(dirname "$0")/.." || exit 1
[[ -f Package.swift ]] || { warn "run this from inside the Keg repo."; exit 1; }
note "repo: $(pwd)"

if ! command -v gh >/dev/null 2>&1; then
  warn "GitHub CLI (gh) is not installed — install it with 'brew install gh' and re-run."
  exit 1
fi
if ! gh auth status >/dev/null 2>&1; then
  warn "gh is installed but not logged in."
  step "Run 'gh auth login' in another terminal, then come back."
  pause "Press Enter once you're logged in."
fi
note "gh: $(gh auth status 2>&1 | grep -m1 'Logged in' || echo 'authenticated')"

if ! xcrun --find notarytool >/dev/null 2>&1; then
  warn "notarytool not found — install Xcode command line tools ('xcode-select --install')."
  exit 1
fi
note "notarytool: present"

# The identity and team ID are already on this machine, so read them rather
# than asking the human to transcribe a string with parentheses in it.
DETECTED_IDENTITY=$(security find-identity -v -p codesigning 2>/dev/null \
  | awk -F'"' '/Developer ID Application:/ { print $2; exit }')
if [[ -z "$DETECTED_IDENTITY" ]]; then
  warn "No 'Developer ID Application' certificate in your keychain."
  step "Create one at https://developer.apple.com/account/resources/certificates"
  step "Download it, double-click to install, then re-run this wizard."
  exit 1
fi
DETECTED_TEAM_ID=$(printf '%s' "$DETECTED_IDENTITY" | sed -n 's/.*(\([A-Z0-9]*\))$/\1/p')
note "identity: $DETECTED_IDENTITY"
note "team:     $DETECTED_TEAM_ID"
pause "Looks right?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Sparkle signing key"
say "Sparkle signs every update with an EdDSA key so Keg can prove a download"
say "really came from you. The public half ships inside the app; the private"
say "half only ever exists in your keychain and in a GitHub secret."

if [[ -s "$PUBLIC_KEY_FILE" ]]; then
  note "$PUBLIC_KEY_FILE already exists: $(cat "$PUBLIC_KEY_FILE")"
  if ! confirm "Generate a NEW key pair? (existing installs would stop accepting updates)"; then
    SPARKLE_PUBLIC_KEY=$(cat "$PUBLIC_KEY_FILE")
    REUSE_SPARKLE_KEY=yes
  fi
fi

if [[ "${REUSE_SPARKLE_KEY:-no}" != "yes" ]]; then
  say "Downloading Sparkle $SPARKLE_VERSION's tools…"
  curl -fsSL -o "$WORK_DIR/sparkle.tar.xz" \
    "https://github.com/sparkle-project/Sparkle/releases/download/$SPARKLE_VERSION/Sparkle-$SPARKLE_VERSION.tar.xz"
  tar -xJf "$WORK_DIR/sparkle.tar.xz" -C "$WORK_DIR"
  GENERATE_KEYS=$(find "$WORK_DIR" -name generate_keys -type f | head -1)
  [[ -n "$GENERATE_KEYS" ]] || { warn "generate_keys not found in the Sparkle tarball."; exit 1; }

  warn "macOS will ask for permission to store the new key in your login keychain."
  "$GENERATE_KEYS" || true

  SPARKLE_PUBLIC_KEY=$("$GENERATE_KEYS" -p 2>/dev/null | tr -d '[:space:]')
  if [[ -z "$SPARKLE_PUBLIC_KEY" ]]; then
    warn "Couldn't read the public key automatically."
    step "Copy the public key printed above (the long base64 string)."
    ask SPARKLE_PUBLIC_KEY "Paste the Sparkle public key:"
  fi

  mkdir -p "$(dirname "$PUBLIC_KEY_FILE")"
  printf '%s' "$SPARKLE_PUBLIC_KEY" > "$PUBLIC_KEY_FILE"
  printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$PUBLIC_KEY_FILE"
  warn "Commit $PUBLIC_KEY_FILE — the Makefile refuses to build a release without it."
fi

say "Exporting the private half for CI…"
if [[ -z "${GENERATE_KEYS:-}" ]]; then
  curl -fsSL -o "$WORK_DIR/sparkle.tar.xz" \
    "https://github.com/sparkle-project/Sparkle/releases/download/$SPARKLE_VERSION/Sparkle-$SPARKLE_VERSION.tar.xz"
  tar -xJf "$WORK_DIR/sparkle.tar.xz" -C "$WORK_DIR"
  GENERATE_KEYS=$(find "$WORK_DIR" -name generate_keys -type f | head -1)
fi
"$GENERATE_KEYS" -x "$WORK_DIR/sparkle_private_key" >/dev/null 2>&1 || true
if [[ -s "$WORK_DIR/sparkle_private_key" ]]; then
  set_secret SPARKLE_PRIVATE_KEY "$(cat "$WORK_DIR/sparkle_private_key")"
  rm -f "$WORK_DIR/sparkle_private_key"
else
  warn "Couldn't export the private key automatically."
  step "Run: $GENERATE_KEYS -x private_key.txt   (then paste its contents below)"
  ask_secret SPARKLE_PRIVATE_KEY "Paste the Sparkle private key:"
  set_secret SPARKLE_PRIVATE_KEY "$SPARKLE_PRIVATE_KEY"
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Developer ID certificate"
say "CI needs your signing certificate as a password-protected .p12 file."
say "Keychain Access can't be scripted for this, so it's a manual export."

open_url "https://support.apple.com/guide/keychain-access/kyca35961/mac"
step "Open Keychain Access (⌘Space, type 'Keychain Access')."
step "Select the 'login' keychain, then the 'My Certificates' category."
step "Find: $DETECTED_IDENTITY"
step "Right-click it → Export… → File Format: Personal Information Exchange (.p12)"
step "Save it to your Desktop as keg-signing.p12."
step "It will ask you to invent a password — pick one and remember it."
pause "Press Enter once the .p12 is saved."

ask CERT_PATH "Path to the .p12 [~/Desktop/keg-signing.p12]:"
CERT_PATH="${CERT_PATH:-$HOME/Desktop/keg-signing.p12}"
CERT_PATH="${CERT_PATH/#\~/$HOME}"
[[ -f "$CERT_PATH" ]] || { warn "No file at $CERT_PATH"; exit 1; }

ask_secret CERT_PASSWORD "The password you just set on the .p12:"

# Prove the password works here rather than discovering it is wrong forty
# minutes into a release build.
if ! openssl pkcs12 -in "$CERT_PATH" -passin pass:"$CERT_PASSWORD" -nokeys -legacy >/dev/null 2>&1 \
   && ! openssl pkcs12 -in "$CERT_PATH" -passin pass:"$CERT_PASSWORD" -nokeys >/dev/null 2>&1; then
  warn "That password doesn't open the .p12. Re-run and try again."
  exit 1
fi
note "password verified against the .p12"

set_secret APPLE_CERTIFICATE "$(base64 -i "$CERT_PATH")"
set_secret APPLE_CERTIFICATE_PASSWORD "$CERT_PASSWORD"
set_secret APPLE_SIGNING_IDENTITY "$DETECTED_IDENTITY"
write_env APPLE_SIGNING_IDENTITY "$DETECTED_IDENTITY"

if confirm "Delete $CERT_PATH now that it's in GitHub?"; then
  rm -f "$CERT_PATH"
  note "deleted $CERT_PATH"
else
  warn "Remember to delete $CERT_PATH — it is your signing identity in a file."
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Notarization credentials"
say "Apple notarizes each build before macOS will open it without warnings."
say "That needs an app-specific password — not your Apple ID password."

open_url "https://account.apple.com/account/manage"
step "Sign in, then find 'App-Specific Passwords' under Sign-In and Security."
step "Click '+', name it 'Keg CI notarization', and copy the generated password."
step "It looks like abcd-efgh-ijkl-mnop and is shown only once."
pause "Press Enter once you've copied it."

ask APPLE_ID "Your Apple ID email:"
ask_secret APPLE_PASSWORD "Paste the app-specific password:"

set_secret APPLE_ID "$APPLE_ID"
set_secret APPLE_PASSWORD "$APPLE_PASSWORD"
set_secret APPLE_TEAM_ID "$DETECTED_TEAM_ID"
write_env APPLE_ID "$APPLE_ID"
write_env APPLE_TEAM_ID "$DETECTED_TEAM_ID"

say "Checking the credentials against Apple…"
if xcrun notarytool history --apple-id "$APPLE_ID" --password "$APPLE_PASSWORD" \
     --team-id "$DETECTED_TEAM_ID" >/dev/null 2>&1; then
  note "Apple accepted the credentials."
else
  warn "Apple rejected them. Double-check the Apple ID and app-specific password."
  confirm "Continue anyway?" || exit 1
fi

if confirm "Also save these to your keychain for local 'make notarize' runs?"; then
  xcrun notarytool store-credentials "keg-notarization" \
    --apple-id "$APPLE_ID" --password "$APPLE_PASSWORD" --team-id "$DETECTED_TEAM_ID" \
    >/dev/null 2>&1 && note "stored as keychain profile 'keg-notarization'" \
    || warn "couldn't store the profile; not fatal"
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Verify"
say "Confirming all seven secrets are present on the repo."

REQUIRED_SECRETS=(
  APPLE_CERTIFICATE APPLE_CERTIFICATE_PASSWORD APPLE_SIGNING_IDENTITY
  APPLE_ID APPLE_PASSWORD APPLE_TEAM_ID SPARKLE_PRIVATE_KEY
)
PRESENT=$(gh secret list --json name --jq '.[].name' 2>/dev/null || echo "")
ALL_PRESENT=yes
for name in "${REQUIRED_SECRETS[@]}"; do
  if printf '%s\n' "$PRESENT" | grep -qx "$name"; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$name"
  else
    printf '  %s✗%s %s\n' "$RED" "$RESET" "$name"
    ALL_PRESENT=no
  fi
done

if [[ -s "$PUBLIC_KEY_FILE" ]]; then
  printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$PUBLIC_KEY_FILE"
else
  printf '  %s✗%s %s\n' "$RED" "$RESET" "$PUBLIC_KEY_FILE"
  ALL_PRESENT=no
fi

printf '\n'
if [[ "$ALL_PRESENT" == "yes" ]]; then
  say "Everything is in place. To cut a release:"
  note "  1. git add $PUBLIC_KEY_FILE && git commit && git push"
  note "  2. gh workflow run release.yml -f version=0.2.0"
  note "  3. Watch it at: gh run watch"
else
  warn "Some values are still missing — re-run this wizard to fill them in."
fi

finish
